### ISSUE TITLE
Seeing a problem while using a remote PostgreSQL

### ISSUE THREAD

**Issue by jcbiz** [pgrok/pgrok#200]
### Type out the question

Hello,

I was trying to start pgrokd 1.4.4 docker container for arm and use a PostgreSQL instance running on a different system.
I believe the database connection was good, and two tables, host_keys and principles, were created by pgrokd. However, this error seems telling me that the web_server logic was trying to connect to a local database. Could anybody please shed some light? Thank you so much in advance.

Jeffrey

This is the error message
```
panic: session: create table: failed to connect to `host=/tmp user=pgrokd database=`: dial error (dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory)

goroutine 11 [running]:
github.com/flamego/session.Sessioner({0x40002a5db0, 0x1, 0x40002a5e88?})
        /home/runner/go/pkg/mod/github.com/flamego/session@v1.6.5/session.go:175 +0x2ec
main.startWebServer(0x4000161500, 0x400005d198)
        /home/runner/work/pgrok/pgrok/pgrokd/cli/web_server.go:102 +0x9a0
created by main.main in goroutine 1
        /home/runner/work/pgrok/pgrok/pgrokd/cli/main.go:46 +0x2b0
```

This is my config file
```
external_url: "http://localhost:3320"

web:
  port: 3320
proxy:
  port: 3330
  scheme: "http"
  domain: "localhost:3330"
sshd:
  port: 2222

database:
  host: "10.0.0.2"
  port: 5432
  user: "pgrokd"
  password: "XXXXXXXX"
  database: "pgrokd"
```

### Consent

- [x] I agree to follow the [Code of Conduct](https://go.dev/conduct)
- [x] I understand a satisfying answer is not guaranteed
